# Generated by Django 5.2.7 on 2025-10-06 21:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('correo_institucional', models.EmailField(max_length=254, unique=True, verbose_name='Correo institucional')),
                ('grupo', models.IntegerField(verbose_name='Grupo/Curso')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MedicionPlantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Día de medición')),
                ('altura_planta1', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Altura Planta 1 (cm)')),
                ('altura_planta2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Altura Planta 2 (cm)')),
                ('altura_planta3', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Altura Planta 3 (cm)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='registros.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Medición de Plantas',
                'verbose_name_plural': 'Mediciones de Plantas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroFotografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='registro_fotografico/', verbose_name='Fotografía')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_fotograficos', to='registros.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Registro Fotográfico',
                'verbose_name_plural': 'Registros Fotográficos',
                'ordering': ['-fecha'],
            },
        ),
    ]
