# Generated by Django 4.2.24 on 2025-10-06 21:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionplantas',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Altura de la planta (cm)'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='medicionplantas',
            unique_together={('estudiante', 'dia')},
        ),
        migrations.RemoveField(
            model_name='medicionplantas',
            name='altura_planta1',
        ),
        migrations.RemoveField(
            model_name='medicionplantas',
            name='altura_planta2',
        ),
        migrations.RemoveField(
            model_name='medicionplantas',
            name='altura_planta3',
        ),
    ]
