# Generated by Django 4.2.24 on 2025-10-20 19:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_medicionplantas_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicionplantas',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Altura de la planta (cm)'),
        ),
    ]
