# Generated by Django 5.2.7 on 2025-10-20 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_medicionplantas_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofotografico',
            name='medicion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='registros.medicionplantas', verbose_name='Medición asociada'),
        ),
    ]
